Implement clj:str
lfe/lfe pull request #291
Opened 2016-10-16 20:20 UTC by skovsgaard

This is an attempt at implementing `clj:str/?`, which constructs a string from possibly disparate values.

Please poke holes in this solution as I'm sure to have overlooked something.

2016-10-16 21:46 UTC, yurrriq requested changes

2016-10-16 21:46 UTC, yurrriq commented on test/clj-tests.lfe
> +  (is-equal "2.00c" (clj:str 2.0 'c)))
Can we add a test or two with a `let` and confirm that `str`-ing a variable works as desired too?

Also, for cases like this where the expected values are literals, I think it's better to use `is-match` so we get more descriptive errors.

2016-10-17 06:51 UTC, skovsgaard commented on test/clj-tests.lfe
> +  (is-equal "2.00c" (clj:str 2.0 'c)))
Yup. I'll make those changes as soon as I can. It should be later today.

2016-10-17 18:43 UTC, yurrriq commented
It basically does what your `clj:str/1` doe but for a single term instead of a list of them. It works fine for me :confused: but notably handles individual characters as integers, which should be documented if not avoided.

```lfe
;; faked based on memory, but you get the idea
(= "65" (clj:str #\a)) 
```

2016-10-17 18:59 UTC, skovsgaard commented
I'm not entirely sure how to avoid that happening. Characters are just integers and I'm not sure how I'd go about differentiating when someone wants a string of "65" and when they want an upper case A.

Where should I document this if it cannot be avoided?

2016-10-17 19:02 UTC, yurrriq commented
In `doc/src/clj.3.md` or similar. Then you can regenerate the docs (with `pandoc` installed) via `make docs` or similar. I'm mobile now.

2016-10-17 19:03 UTC, skovsgaard commented
Okay. I'll try doing that. Thank you.

2016-10-17 20:40 UTC, yurrriq commented
Oh, I meant something like `(let ((x ...)) (clj:str x ...))`.

2016-10-17 20:40 UTC, skovsgaard commented
Okay, I added the docs and generated again. I really hope there's a project policy to only use `1.17.1` of Pandoc. Otherwise I just jumped through a lot of unnecessary install hoops.

Also should I replace the `let` tests with what you meant or just add it after them?

2016-10-17 20:46 UTC, yurrriq commented
The more tests the merrier. We don't have a strict version requirement for `pandoc` but it can't hurt to use that same as Robert. I think I use a more recent version...

2016-10-17 20:50 UTC, skovsgaard commented
Cool. I added two tests for use within a `let`.

2016-10-17 20:56 UTC, yurrriq commented
Comparing the Erlang implementation of `lfe_io_write:term/1` (which is what `lfe_io:print1/1` calls under the hood) and the current`clj:str` macro. I think we should replace the ad hoc `match-lambda` with a call to `lfe_io:print1/1`. What was the issue you had with that, @skovsgaard?

```erlang
term(S) -> term(S, -1).                         %All the way

term(_, 0) -> "...";
term(Symb, _) when is_atom(Symb) -> symbol(Symb);
term(Numb,_ ) when is_integer(Numb) -> integer_to_list(Numb);
term(Numb, _) when is_float(Numb) -> io_lib_format:fwrite_g(Numb);
term(List, D) when is_list(List) ->
    [$(,list(List, D-1),$)];
term({}, _) -> "#()";
term(Vec, D) when is_tuple(Vec) ->
    Es = tuple_to_list(Vec),
    ["#(",list(Es, D-1),")"];
term(Bit, _) when is_bitstring(Bit) ->
    bitstring(Bit);
term(Map, D) when ?IS_MAP(Map) -> map(Map, D);
term(Other, D) ->                               %Use standard Erlang for rest
    io_lib:write(Other, D).
```

```lfe
(defmacro str args
  "Construct a string from an arbitrary number of scalar values."
  `(lists:flatmap
    (match-lambda
      ([x] (when (is_integer x))
       (integer_to_list x))
      ([x] (when (is_float x))
       (float_to_list x '(#(decimals 2))))
      ([x] (when (is_atom x))
       (atom_to_list x))
      ([x] (when (is_binary x))
       (binary_to_list x))
      ([x] x))
    (list ,@args)))
```

I guess we'll want an `if` form to check for `clj:string?` so we don't print `"string"` as `(115 116 114 105 110 103)`.

2016-10-17 21:00 UTC, yurrriq commented
```lfe
> (include-lib "lfe/include/clj.lfe")
identical?
> (defmacro str args
    `(lists:flatmap
       (fn [arg] (cond-> arg (not (clj:string? arg)) (lfe_io:print1)))
       (list ,@args)))
str
> (let ((test "test")) (str test 'ing " " 123))
"testing 123"
```

2016-10-17 21:01 UTC, skovsgaard commented
I didn't actually have an issue with it. I was just curious about the benefit of it, but if it reduces the amount of code and/or gets rid of the issue with characters, I'm all for it.

2016-10-17 21:02 UTC, skovsgaard commented
Let me just change it one sec and run it with the current tests.

2016-10-17 21:03 UTC, yurrriq commented
Cool. It reduces redundancy, for sure, but *does not* get rid of the issue with characters. I don't think there's a sensible way to do that, so we ought to just document the behaviour, suggesting to use e.g. `"-"` instead of `#\-` and give examples of both results in the docs.

2016-10-17 21:04 UTC, yurrriq commented
Contrived examples:

```lfe
> (clj:str "not hyphen" #\- "ated")
"not hyphen45ated"
> (clj:str "hyphen" "-" "ated")
"hyphen-ated"
```

2016-10-17 21:17 UTC, skovsgaard commented
Okay, I'm not sure how to make this work for tests too. I can't not call `include-lib` unless I wanna be a lot of stuff short, but I also can't place it in the include file because then I'm missing `string?`. Is there a way around this?

2016-10-17 21:20 UTC, yurrriq commented
I'm not sure I understand. The definition of `str` should be in `clj.lfe` so the `include-lib` call is unnecessary. I was just playing around in a shell. For the tests, you'll make a fully qualified call to `clj:str`.

2016-10-17 21:21 UTC, yurrriq commented
This (or similar) should work:

```lfe
(defmacro str args
  `(lists:flatmap
    (lambda (arg)
      (clj:cond-> arg (not (clj:string? arg)) (lfe_io:print1)))
    (list ,@args)))
```

2016-10-17 21:27 UTC, skovsgaard commented
I got that to work. I wasn't thinking and just calling stuff without `clj:` prepended. Also this approach seems to treat floats a lot better than both mine and `lists:concat` do.

2016-10-17 21:27 UTC, yurrriq commented
I've got a PR for you. Hang on.

2016-10-17 21:51 UTC, yurrriq commented
https://github.com/skovsgaard/lfe/pull/1

2016-10-17 21:56 UTC, skovsgaard commented
Okay, it's merged.

2016-10-17 22:00 UTC, yurrriq commented
@rvirding, I think we're good to merge here. Note that this PR closes #269.

2016-10-17 22:01 UTC, skovsgaard commented
Cool. I'll close the issue on this.

2016-10-17 22:03 UTC, skovsgaard commented
Perfect. Just let me know if there's anything else missing on my end.

2016-10-17 22:54 UTC, yurrriq commented
For the record I'm on 1.17.1 too.

2016-10-19 02:24 UTC, rvirding commented
I'm on pandoc 1.17.0.2 but if there are any problems I will upgrade.

2016-10-19 02:26 UTC, merged